[build]
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  included_files = ["!public/**", "!.next/cache/**", "!.next/static/**", "!node_modules/.cache/**"]

[build.environment]
  NODE_VERSION = "20"
  NEXT_FORCE_EDGE_IMAGES = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

